baseURL = 'https://www.abdisalam.blog/'
languageCode = 'en-us'
title = 'Sir Abdisalam | The Website'

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[server]
  watch = false

[build]
  noJSConfigInAssets = true
  buildFuture = true

[params]
mainSections = ["blog"]
